# These are the constants for plusMinusEstimator


# These are reflected in seconds
CALL_TIME_INTERVAL = 30
MOMENTUM_INTERVAL = 180

SECONDS_PER_PERIOD = 720
NUMBER_OF_PERIODS = 4

STATUS_IN_PROGRESS = 'STATUS_IN_PROGRESS'
STATUS_SCHEDULED = 'STATUS_SCHEDULED'
STATUS_POSTPONED = 'STATUS_POSTPONED'
